trainer:
  gpus: [1,2]
  precision: 16
  gradient_clip_val: 1.0
  overfit_batches: 100
  max_epochs: 150
  weights_save_path: /raid/scratch/wuws/docker/v12_weighted_mapq/model/v17
  val_check_interval: 0.2
model:
  gru_input_dim: 128
  gru_hidden_dim: 128
  gru_n_layers: 1
  gru_dropout: 0.0
  attn_embed_dim: 128
  attn_n_heads: 8
  attn_n_blocks: 8
  attn_depth_prob: 1.0
  attn_pos_dropout: 0.1
data:
  data_dir: /mnt/projects/miles-wgs-wenshan/wuws_m/v12/v12_train
  val_path: /mnt/projects/miles-wgs-wenshan/wuws_m/v12/v12_val
  batch_size: 32
  mem: False
  workers: 4